title: Demirtaş Lab
description: Cancer Metabolism Research Laboratory
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
header_pages:
  - index.md
  - research.md
  - publications.md
  - projects.md
  - team.md
  - contact.md
