title: Demirtaş Lab
description: Molecular Cancer Research Laboratory
baseurl: ""
url: "https://demirtaslab.github.io"

theme: null

markdown: kramdown

include:
  - _pages

collections:
  team:
  publications:
  projects:
